## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

title = "Flowkeeper"
copyright = "{year}"

## -----------------------------------------------
## Publish
## -----------------------------------------------

relativeURLs = "true"
#canonifyURLs = "true"

# Local
baseURL = "/"
publishDir = "public"

# Remote
#baseURL = "https://caressofsteel.github.io/demos/hugo/hugo-story/"
#publishDir = "//centos/sites/hugodev/hugostory/"

## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "section"]
# googleAnalytics = "G-XXXXXXXXXX"

## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
  description = "Flowkeeper is a Pomodoro Technique desktop timer for power users and professional teams"
  logo = "images/logo.svg"
  favicon = true

[Params.social]
  github = "https://github.com/flowkeeper-org/fk-desktop"
  email = "contact@flowkeeper.org"
  linkedin = "https://www.linkedin.com/company/flowkeeper-org"
  discord = "https://discord.gg/MCbxbmjv"
  reddit = "https://www.reddit.com/r/Flowkeeper/"
  telegram = "https://t.me/flowkeeper_org"

[Params.asset]
  fontawesome_css = ["css/fontawesome-all.min.css"]
  fontawesome_js = ["js/fontawesome-all.min.js"]
